name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kv_server
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            git \
            libboost-all-dev \
            libgtest-dev \
            libpq-dev \
            postgresql-client \
            python3

      - name: Create database schema
        env:
          PGPASSWORD: 1234
        run: |
          psql \
            -h 127.0.0.1 \
            -U kv_user \
            -d kv_server \
            -c "
              CREATE TABLE IF NOT EXISTS kv_store (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
              );
            "

      - name: Run tests
        env:
          PGHOST: 127.0.0.1
          PGPORT: 5432
          PGDATABASE: kv_server
          PGUSER: kv_user
          PGPASSWORD: 1234
        run: |
          chmod +x ./scripts/full_test.sh
          ./scripts/full_test.sh