name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: kv_user
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: kv_server

        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U kv_user -d kv_server"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            cmake \
            g++ \
            libboost-all-dev \
            libgtest-dev \
            libpq-dev \
            postgresql-client \
            python3

      - name: Create database schema
        env:
          PGPASSWORD: 1234
        run: |
          psql \
            -h localhost \
            -p 5432 \
            -U kv_user \
            -d kv_server \
            -c "
              CREATE TABLE IF NOT EXISTS kv_store (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
              );
            "
      - name: Configure project
        run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=ON
            
      - name: Build project
        run: |
          cmake --build build --parallel
        
      - name: Run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh